#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
PURPLE="\033[0;35m"
YELLOW="\033[0;33m"
NC="\033[0m"

echo -e ${GREEN}Installing ${PURPLE}duppsolc ${GREEN} to ${YELLOW}/usr/local/bin${GREEN}!${NC}

DUPPSOLC='#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
PURPLE="\033[0;35m"
YELLOW="\033[0;33m"
NC="\033[0m"

if [[ -z $1 ]]
then
    VERSION="ALL"

else
    VERSION=$1
    SOLC=".solc_$(echo "$1" | sed -e "s/\./\_/g")"
fi

echo -e ${GREEN}Installing ${PURPLE}DappTools ${GREEN}solc-static-version ${YELLOW}${VERSION}${GREEN}!${NC}
nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions"${SOLC}"'

BINARY="/usr/local/bin/dappsolc"
echo "$DUPPSOLC" > $BINARY
chmod +x $BINARY